"""add constraint and timetable tables

Revision ID: 0171e95787c9
Revises: fb1a5dbc0f00
Create Date: 2026-02-22 21:03:29.971530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0171e95787c9'
down_revision: Union[str, None] = 'fb1a5dbc0f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('TEACHER', 'SUBJECT', 'CLASS', 'GROUPING', 'GLOBAL', name='constraintcategory'), nullable=False),
    sa.Column('type', sa.Enum('HARD', 'SOFT', name='constrainttype'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('BLOCK_TIMESLOT', 'BLOCK_DAY', 'BLOCK_TIME_RANGE', 'PREFER_TIME_RANGE', 'PREFER_TIMESLOT', 'AVOID_LAST_PERIOD', 'MAX_PER_DAY', 'MIN_DAYS_SPREAD', 'NO_CONSECUTIVE_DAYS', 'REQUIRE_CONSECUTIVE_PERIODS', 'SAME_DAY_GROUPING', 'NOT_SAME_DAY_AS', 'MAX_TEACHING_HOURS_PER_DAY', 'MIN_TEACHING_HOURS_PER_DAY', 'MAX_TEACHING_DAYS', 'MIN_FREE_DAYS', 'BALANCED_DAILY_LOAD', 'NO_GAPS', 'MAX_GAPS_PER_DAY', 'MAX_GAPS_PER_WEEK', 'SYNC_TRACKS', 'SYNC_TEACHER_CLASSES', 'EARLY_FINISH', 'MINIMIZE_TEACHER_DAYS', 'CLASS_DAY_LENGTH_LIMIT', 'TEACHER_FIRST_LAST_PREFERENCE', name='ruletype'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('target_type', sa.Enum('TEACHER', 'SUBJECT', 'CLASS', 'GRADE', 'ALL', name='targettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('solve_time_seconds', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'TIMEOUT', name='solutionstatus'), nullable=False),
    sa.Column('scenario_name', sa.String(length=300), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_lessons')
    op.drop_table('solutions')
    op.drop_table('constraints')
    # ### end Alembic commands ###
