"""add min_work_days to teachers

Revision ID: 3a74d477d6f0
Revises: 50428c8ef324
Create Date: 2026-04-07 02:18:52.327569
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a74d477d6f0'
down_revision: Union[str, None] = '50428c8ef324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_groups', 'homeroom_daily_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('class_groups', 'homeroom_is_hard')
    op.drop_column('class_groups', 'homeroom_early_sunday_weight')
    op.drop_column('class_groups', 'homeroom_weight')
    op.drop_column('class_groups', 'homeroom_early_other_weight')
    op.drop_column('class_groups', 'num_students')
    op.drop_column('class_groups', 'homeroom_min_days')
    op.alter_column('constraints', 'target_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('TEACHER', 'SUBJECT', 'CLASS', 'GRADE', 'GROUPING', 'ALL', name='targettype'),
               existing_nullable=False)
    op.create_foreign_key(None, 'grouping_clusters', 'grades', ['grade_id'], ['id'])
    op.alter_column('meetings', 'is_mandatory_attendance',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('meetings', 'allow_overlap',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('meetings', 'require_consecutive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('schools', 'max_consecutive_meetings',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.drop_column('schools', 'homeroom_min_days')
    op.alter_column('subject_requirements', 'always_double',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subject_requirements', 'allow_overlap',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subject_requirements', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'limit_last_periods',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('teachers', sa.Column('min_work_days', sa.Integer(), nullable=True))
    op.drop_column('teachers', 'needs_transport')
    op.alter_column('tracks', 'pinned_slots',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tracks', 'allow_overlap',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'tracks', 'subject_requirements', ['requirement_id'], ['id'])
    op.create_foreign_key(None, 'tracks', 'class_groups', ['source_class_id'], ['id'])
    op.drop_column('tracks', 'require_consecutive')
    op.drop_column('tracks', 'is_secondary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('is_secondary', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.add_column('tracks', sa.Column('require_consecutive', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.alter_column('tracks', 'allow_overlap',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tracks', 'pinned_slots',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('teachers', sa.Column('needs_transport', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.drop_column('teachers', 'min_work_days')
    op.alter_column('subjects', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'limit_last_periods',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subject_requirements', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subject_requirements', 'allow_overlap',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subject_requirements', 'always_double',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('schools', sa.Column('homeroom_min_days', sa.INTEGER(), server_default=sa.text("'4'"), nullable=True))
    op.alter_column('schools', 'max_consecutive_meetings',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.alter_column('meetings', 'require_consecutive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('meetings', 'allow_overlap',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('meetings', 'is_mandatory_attendance',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'grouping_clusters', type_='foreignkey')
    op.alter_column('constraints', 'target_type',
               existing_type=sa.Enum('TEACHER', 'SUBJECT', 'CLASS', 'GRADE', 'GROUPING', 'ALL', name='targettype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.add_column('class_groups', sa.Column('homeroom_min_days', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True))
    op.add_column('class_groups', sa.Column('num_students', sa.INTEGER(), nullable=False))
    op.add_column('class_groups', sa.Column('homeroom_early_other_weight', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True))
    op.add_column('class_groups', sa.Column('homeroom_weight', sa.INTEGER(), server_default=sa.text('(95)'), nullable=True))
    op.add_column('class_groups', sa.Column('homeroom_early_sunday_weight', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True))
    op.add_column('class_groups', sa.Column('homeroom_is_hard', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.alter_column('class_groups', 'homeroom_daily_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
