"""add grade_id to grouping_clusters

Revision ID: 713d3fb1e4e0
Revises: b959587f1dca
Create Date: 2026-03-04 08:40:46.945773
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713d3fb1e4e0'
down_revision: Union[str, None] = 'b959587f1dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = {c["name"] for c in inspector.get_columns("grouping_clusters")}
    if "grade_id" not in cols:
        op.add_column('grouping_clusters', sa.Column('grade_id', sa.Integer(), nullable=True))

    # Backfill grade_id from first source class
    conn.execute(sa.text("""
        UPDATE grouping_clusters
        SET grade_id = (
            SELECT cg.grade_id
            FROM cluster_source_classes csc
            JOIN class_groups cg ON cg.id = csc.class_group_id
            WHERE csc.cluster_id = grouping_clusters.id
            LIMIT 1
        )
        WHERE grade_id IS NULL
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grouping_clusters', type_='foreignkey')
    op.drop_column('grouping_clusters', 'grade_id')
    # ### end Alembic commands ###
