"""add teacher extra roles and meeting system

Revision ID: 87a96633d8ef
Revises: 8ef2ec7c524b
Create Date: 2026-03-03 03:11:38.001784
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a96633d8ef'
down_revision: Union[str, None] = '8ef2ec7c524b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('meeting_type', sa.String(length=20), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_teachers',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'teacher_id')
    )
    op.add_column('teachers', sa.Column('is_counselor', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('teachers', sa.Column('is_principal', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('teachers', sa.Column('is_pedagogical_coordinator', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('teachers', sa.Column('is_director', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'is_director')
    op.drop_column('teachers', 'is_pedagogical_coordinator')
    op.drop_column('teachers', 'is_principal')
    op.drop_column('teachers', 'is_counselor')
    op.drop_table('meeting_teachers')
    op.drop_table('scheduled_meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
