"""add periods_per_day_map to schools

Revision ID: 937bb2e92653
Revises: 0171e95787c9
Create Date: 2026-02-22 21:51:57.528736
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937bb2e92653'
down_revision: Union[str, None] = '0171e95787c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('periods_per_day_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'periods_per_day_map')
    # ### end Alembic commands ###
