"""add co_teacher_ids to subject_requirements

Revision ID: b959587f1dca
Revises: ea8d3466f039
Create Date: 2026-03-04 08:31:26.572441
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b959587f1dca'
down_revision: Union[str, None] = 'ea8d3466f039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_requirements', sa.Column('co_teacher_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_requirements', 'co_teacher_ids')
    # ### end Alembic commands ###
