"""add is_external to subject_requirements

Revision ID: fcffaa543fe0
Revises: 22ebfc8d71c8
Create Date: 2026-03-03 03:46:24.496642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcffaa543fe0'
down_revision: Union[str, None] = '22ebfc8d71c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_requirements', sa.Column('is_external', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_requirements', 'is_external')
    # ### end Alembic commands ###
